### ISSUE TITLE
Support for other browsers

### ISSUE THREAD

**Issue by hawkeng** [jopemachine/alfred-chrome-workflow#12]
First of all, thanks for creating this workflow, it has been really helpful!

I wanted to know what are your thoughts on extending the config file to support more Chromium-based browsers? 

I use Brave Browser, so I had to fork this repo and tweak the code a bit to make it work with Brave. 
Instead of just adding a new URL to `getDBFilePath` I figured I could make it even more flexible if I just included a config property that allowed me to specify the browser support directory. 

You can check my commit [here](https://github.com/hawkeng/alfred-chrome-workflow/commit/2503083a953d5a64ab8e43e789576cd56afc3793).

If you agree and are okay with the changes, I can create a PR, otherwise thanks for your time.

**Comment by jopemachine** [comment]
Sure, I'm glad to hear that this workflow is useful to you.

I think it makes sense to create `browser_dir` option  to support more other chromium-based browsers.

Please feel free to make a PR about this.

I appreciate your contribution.

**Comment by jun6lee** [comment]
I haven't been as elegant as @hawkeng, but have nonetheless added Brave support as a pull request.
