### ISSUE TITLE
unable to install worlflow

### ISSUE THREAD

**Issue by ShubhamJ010** [jopemachine/alfred-chrome-workflow#14]
Kept running the the command provided
It show the following prompts and when i check the workflow section its empty
<img width="553" alt="Screenshot 2022-02-04 at 4 56 50 PM" src="https://user-images.githubusercontent.com/40000538/152521342-d69a4cdc-76fa-4274-9946-944aa8e96f5d.png">

**Comment by jopemachine** [comment]
Please try to install again with this command `npm i -g alfred-chrome-workflow`.
You missed the `-g` flag.

**Comment by ShubhamJ010** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/40000538/156550715-3b49e987-a8a5-4877-bc16-5d203f7d3ca1.png">

**I am still stuck please help me**

**Comment by jopemachine** [comment]
It seems that many user are stuck with the issue, maybe I need to write more descriptions about installation to readme..
Please refer to below comment to resolve this.
https://github.com/jopemachine/alfred-chrome-workflow/issues/5#issuecomment-917042964
