### ISSUE TITLE
Can't install - need Admin access?

### ISSUE THREAD

**Issue by Alvt5** [jopemachine/alfred-chrome-workflow#15]
I downloaded latest nom and the latest workflow code.

Keep getting this error 
npm install --global alfred-chrome-workflow
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules/alfred-chrome-workflow
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/alfred-chrome-workflow'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/alfred-chrome-workflow'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/alfred-chrome-workflow'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alvin/.npm/_logs/2022-02-24T13_28_27_661Z-debug-0.log

Any ideas?

**Comment by jopemachine** [comment]
It seems that you don't have permission under the `/usr/local/lib/node_modules` path.

You can check the issue [here](https://github.com/jopemachine/alfred-chrome-workflow/issues/5#issuecomment-917042964) and try the method.

**Comment by Alvt5** [comment]
great that worked!
Any plans for extending it to safari?

**Comment by jopemachine** [comment]
> great that worked! Any plans for extending it to safari?

I'm not planning to extend this workflow for being now.
(Closed due to resolve the issue.)
